### ISSUE TITLE
Windows构建过程中的问题

### ISSUE THREAD

**Issue by XiaoXueTu555** [Sunrisepeak/KHistory#18]
我不会用xmake，然后照着构建文档在命令行中构建此项目。下面是我在命令行中的输入以及输出的内容。

PS C:\Users\XiaoXueTu\Downloads\KHistory-main> xmake
checking for platform ... windows
checking for architecture ... x64
checking for Microsoft Visual Studio (x64) version ... 2022
checking for Microsoft C/C++ Compiler (x64) version ... 19.38.33135
note: install or modify (m) these packages (pass -y to skip confirm)?
in xmake-repo:
  -> imgui v1.89-docking [runtimes:"MT", glfw_opengl3:y]
please input: y (y/n/m)
y
  => clone https://github.com/ocornut/imgui.git v1.89-docking .. failed

we can also download these packages manually:
  - https://github.com/ocornut/imgui.git
to the local search directories: /D:\GitHub
  - imgui
and we can run `xmake g --pkg_searchdirs=/xxx` to set the search directories.
error: Cloning into 'source.tmp\imgui'...
fatal: unable to access 'https://github.com/ocornut/imgui.git/': Failed to connect to github.com port 443 after 21027 ms: Couldn't connect to server

这貌似是在获取imgui时的错误，由于连接超时所造成，但是我的电脑可以正常的访问imgui的仓库，也可以正常的从imgui仓库中获取源代码，造成这个原因是什么？
我可以自己下载imgui的源代码，然后在构建此项目的过程中手动指定它吗？

**Comment by XiaoXueTu555** [comment]
我大概知道了问题所在，我发现当我使用git来clone imgui仓库的时候会报连接超时的错误，跟上面这个一样，所以说xmake其实是在调用git？

**Comment by Sunrisepeak** [comment]
> 我大概知道了问题所在，我发现当我使用git来clone imgui仓库的时候会报连接超时的错误，跟上面这个一样，所以说xmake其实是在调用git？

是的 xmake 需要通过git 获取依赖包的代码。

要自己配置imgui, 把下面的自动依赖删除, 并添加本地的imgui对应的头文件路径也可以

https://github.com/Sunrisepeak/KHistory/blob/38b44128f05bc4b7bbe9f4e7bf93f518dd0134f7/xmake.lua#L8-L9

**Comment by XiaoXueTu555** [comment]
> > 我大概知道了问题所在，我发现当我使用git来clone imgui仓库的时候会报连接超时的错误，跟上面这个一样，所以说xmake其实是在调用git？
> 
> 是的 xmake 需要通过git 获取依赖包的代码。
> 
> 要自己配置imgui, 把下面的自动依赖删除, 并添加本地的imgui对应的头文件路径也可以
> 
> https://github.com/Sunrisepeak/KHistory/blob/38b44128f05bc4b7bbe9f4e7bf93f518dd0134f7/xmake.lua#L8-L9

谢谢你的回复，不过我的确不会用xmake，不知道如何修改xmake.lua文件，你可以详细的讲解一下如何添加本地的imgui吗？我的imgui放在了"D:\GitHub\imgui"路径

**Comment by Sunrisepeak** [comment]
> > > 我大概知道了问题所在，我发现当我使用git来clone imgui仓库的时候会报连接超时的错误，跟上面这个一样，所以说xmake其实是在调用git？
> > 
> > 
> > 是的 xmake 需要通过git 获取依赖包的代码。
> > 要自己配置imgui, 把下面的自动依赖删除, 并添加本地的imgui对应的头文件路径也可以
> > https://github.com/Sunrisepeak/KHistory/blob/38b44128f05bc4b7bbe9f4e7bf93f518dd0134f7/xmake.lua#L8-L9
> 
> 谢谢你的回复，不过我的确不会用xmake，不知道如何修改xmake.lua文件，你可以详细的讲解一下如何添加本地的imgui吗？我的imgui放在了"D:\GitHub\imgui"路径

这个本质是配置imgui, xmake只要把头文件和.cpp配置一下就可以了

```
add_includedirs("yourImguiIncludePath")
add_files("yourImguiSrcPath/*.cpp")
```

手动构建imgui具体可以查看 https://github.com/ocornut/imgui
更多xmake文档可以查看 https://xmake.io/#/zh-cn/guide/quickstart

**个人感觉, 本地git问题解决一下, 就不用自己配置了。这样效率会快一些**

**Comment by Sunrisepeak** [comment]
或者使用 xmake g --pkg_searchdirs=/xxx 配置下imgui的路径试一试

**Comment by Sunrisepeak** [comment]
这里也有编译好的可以用

https://github.com/Sunrisepeak/KHistory/releases

**Comment by XiaoXueTu555** [comment]
我已经配置好了imgui（我才知道xmake里面也有转义字符，导致一直对我的路径报错）。
但是现在产生了新的问题：
error: KeyHistory.cpp
include\KeyHistory.h(20): fatal error C1083: 无法打开包括文件: “dstruct.hpp”: No such file or directory

  > in src\KeyHistory.cpp

**Comment by Sunrisepeak** [comment]
> 我已经配置好了imgui（我才知道xmake里面也有转义字符，导致一直对我的路径报错）。
> 
> 但是现在产生了新的问题：
> 
> error: KeyHistory.cpp
> 
> include\KeyHistory.h(20): fatal error C1083: 无法打开包括文件: “dstruct.hpp”: No such file or directory
> 
> 
> 
>   > in src\KeyHistory.cpp
> 
>   

克隆项目的时候需要 加上 --recursive 把子项目也现在下来。 具体你可以看下 third party 目录下的子模块

**Comment by XiaoXueTu555** [comment]
> > 我已经配置好了imgui（我才知道xmake里面也有转义字符，导致一直对我的路径报错）。
> > 但是现在产生了新的问题：
> > error: KeyHistory.cpp
> > include\KeyHistory.h(20): fatal error C1083: 无法打开包括文件: “dstruct.hpp”: No such file or directory
> > > in src\KeyHistory.cpp
> 
> 克隆项目的时候需要 加上 --recursive 把子项目也现在下来。 具体你可以看下 third party 目录下的子模块

谢谢你！我成功的用Visual Studio 2022构建了这个项目！
我的git始终无法clone任何GitHub上的仓库，搞了一天，最终我尝试配置GitHub的镜像站（gitclone），最后用xmake成功配置出了VS2022的项目，现在我可以运行它了。

**Comment by XiaoXueTu555** [comment]
![image](https://github.com/user-attachments/assets/2078cafe-ef90-4e75-8f59-667239958a63)
在你的帮助下我学习了很多东西，谢谢你~ 
我将会点一个star并且给你的视频一键三连，这是你应得的

**Comment by Sunrisepeak** [comment]
@XiaoXueTu555 
该项目近期可能会进行一次大的重构并添加一些新特性。欢迎持续关注或尝试参与项目的开发。该问题先关闭, 后续有其他问题可以再提新的issue
